export const sampleAccommodations = [
    {
        "name": "Tranquil Garden House",
        "description": "This house is perfect for families and small groups of friends. Beautifully located in the residential neighborhood of San Rafael. Just a block away you have food, health clinics, markets and the main street of the city where you can take the bus to go to the different nearby beaches and the downtown area.\n\nInside the property you will experience a nice breeze. You will have a spacious living and dining room, kitchen, 2 Bedrooms, 1 Bathroom, patio and internal parking.\n\nRelax and enjoy in the jacuzzi at the quiet patio!",
        "house_rules": "A maximum of 4 people is allowed inside the house.\n\nLoud music is not allowed after 10PM.",
        "amenities": ["Wifi", "Dedicated workspace", "Free parking on premises", "Hot tub", "TV", "Air conditioning", "Hair dryer", "Hangers", "Iron", "Kitchen", "Carbon monoxide alarm", "Smoke alarm", "Single level home"],
        "price": 105.0,
        "security_deposit": 500,
        "cleaning_fee": 15,
        "extra_people": 0,
        "number_of_reviews": 6,
        "review_scores_rating": 93,
        "review_scores_accuracy": 10,
        "review_scores_cleanliness": 10,
        "review_scores_checkin": 10,
        "review_scores_communication": 10,
        "review_scores_location": 9,
        "review_scores_value": 9,
        "host_id": 147551068,
        "host_name": "Luz",
        "host_since": "2017-08-27",
        "host_location": "Bello, Antioquia, Colombia",
        "host_about": "Hola, mucho gusto mi nombre es Luz y soy Administradora de Empresas, vivo en Santa Marta, una ciudad hermosa y mágica donde podrás disfrutar de las mejores playas de Colombia y de un excelente clima.\nme encanta viajar y conocer nuevos lugares.\nEspero atenderte y que tu estancia en mi casa sea inolvidable.",
        "host_response_time": "within an hour",
        "host_response_rate": 100,
        "host_is_superhost": true,
        "host_neighbourhood": "San Rafael",
        "host_has_profile_pic": true,
        "host_identity_verified": true,
        "latitude": 11.23301,
        "longitude": -74.19532,
        "is_location_exact": true,
        "property_type": "House",
        "room_type": "Entire home/apt",
        "accommodates": 4,
        "bathrooms": 1.0,
        "bedrooms": 2,
        "beds": 3,
        "bed_type": "Real Bed"
    },
    {
        "name": "Cozy Apartment near Beaches",
        "description": "It is a independent apartament inside of our big house. It is fully equiped, and centrally located in a quiet residencial neighborhood call \"San Rafael\". Near to the property you will find supermakets, pharmacies, medical clinics, and the public station to the best beachs of Santa Marta.\n\nIt is cozy, very quiet and has a nice natural illumination. Perfectly for couple looking for high quality standards at a lower price in the beatuiful Santa Marta city.",
        "house_rules": "No loud misic after 10PM No more thand 2 people inside the house",
        "amenities": ["Wifi", "Dedicated workspace", "Free parking on premises", "Hot tub", "TV", "Air conditioning", "Hair dryer", "Hangers", "Iron", "Kitchen", "Carbon monoxide alarm", "Smoke alarm", "Single level home"],
        "price": 85.0,
        "security_deposit": 500,
        "cleaning_fee": 15,
        "extra_people": 0,
        "number_of_reviews": 11,
        "review_scores_rating": 96,
        "review_scores_accuracy": 10,
        "review_scores_cleanliness": 10,
        "review_scores_checkin": 10,
        "review_scores_communication": 10,
        "review_scores_location": 9,
        "review_scores_value": 10,
        "host_id": 147551068,
        "host_name": "Luz",
        "host_since": "2017-08-27",
        "host_location": "Bello, Antioquia, Colombia",
        "host_about": "Hola, mucho gusto...",
        "host_response_time": "within an hour",
        "host_response_rate": 100,
        "host_is_superhost": true,
        "host_neighbourhood": "San Rafael",
        "host_has_profile_pic": true,
        "host_identity_verified": true,
        "latitude": 11.23301,
        "longitude": -74.19532,
        "is_location_exact": true,
        "property_type": "Apartment",
        "room_type": "Entire home/apt",
        "accommodates": 2,
        "bathrooms": 1.0,
        "bedrooms": 1,
        "beds": 1,
        "bed_type": "Real Bed"
    }
];
